
u1 = User.create(username: 'guest', password: 'password')
u2 = User.create(username: 'bob', password: 'password')
# u3 = User.create(username: 'charles', password: 'password')
# u4 = User.create(username: 'dan', password: 'password')
# u5 = User.create(username: 'earl', password: 'password')
# u6 = User.create(username: 'fiona', password: 'password')
# u7 = User.create(username: 'george', password: 'password')
# u8 = User.create(username: 'hilary', password: 'password')
# u9 = User.create(username: 'ira', password: 'password')
# u10 = User.create(username: 'jason', password: 'password')

p1 = u1.projects.create(title: 'Growing Tales', target_amount: 100000, end_date: DateTime.strptime("09/25/2017", "%m/%d/%Y"), category_id:1, description: "Nulla vulputate auctor magna ac euismod. Suspendisse condimentum justo massa, eu venenatis quam congue eget. Cras euismod a nulla sed hendrerit. Nullam quis commodo ipsum. Suspendisse efficitur, enim ac interdum vulputate, dui lectus fringilla libero, vitae tempus libero elit quis lacus. Vivamus quis elementum magna, ac eleifend felis. Maecenas gravida nunc sit amet dolor dapibus, in euismod velit eleifend. Duis consectetur vel lacus sed tristique. Nam a fermentum nunc. Maecenas sollicitudin gravida velit. Nam venenatis rhoncus orci id volutpat. Integer vitae suscipit lacus, id aliquet tellus. Suspendisse sed elit eget est sodales lobortis vel nec felis. Vestibulum vitae elementum turpis. Donec nec ex leo. Vivamus volutpat est turpis, quis euismod magna maximus sit amet.")

# b1 = p1.backs.create(user_id: 2, project_id: 1, amount: 100 )
# b2 = p1.backs.create(user_id: 3, project_id: 1, amount: 200 )
# b3 = p1.backs.create(user_id: 4, project_id: 1, amount: 300 )
# b4 = p1.backs.create(user_id: 5, project_id: 1, amount: 400 )
# b5 = p1.backs.create(user_id: 6, project_id: 1, amount: 500 )
# b6 = p1.backs.create(user_id: 7, project_id: 1, amount: 600 )
# b7 = p1.backs.create(user_id: 8, project_id: 1, amount: 700 )
# b8 = p1.backs.create(user_id: 9, project_id: 1, amount: 800 )
